import { BlogPost } from "./types";

export const MLBB_BLOGS_DATA: BlogPost[] = [

  {
    id: "6",
    title: "99% Players Donâ€™t Know These MLBB Tricks (Rank Up Instantly)",
    slug: "mlbb-tricks-to-rank-up",
    game: "mlbb",
    type: "Pro Tips",
    excerpt:
      "Master the hidden mechanics of Mobile Legends that pro players use to dominate Every match. Learn advanced minimap tricks, jungle pathing, and item countering.",
    publishedAt: "2026-03-29",
    author: "Admin",
    authorRole: "Expert Mythic Player",
    readingTime: "6 min read",
    image: "/blog/mlbb-tricks.png",
    featured: true,
    keywords: ["mlbb tricks", "rank up fast mlbb", "mobile legends tips 2026"],
    tags: ["Ranking", "Advanced", "Gameplay"],
  },
  {
    id: "7",
    title: "Stop Losing in Mobile Legends â€“ Fix These 7 Mistakes Now",
    slug: "stop-losing-mlbb-7-mistakes",
    game: "mlbb",
    type: "Guide",
    excerpt:
      "Are you stuck in Epic or Legend rank? You might be making these 7 common mistakes. Learn how to fix your gameplay and start winning in Mobile Legends.",
    publishedAt: "2026-03-29",
    author: "Admin",
    authorRole: "Pro Coach",
    readingTime: "7 min read",
    image: "/blog/fix-mistakes.png",
    keywords: ["stop losing mlbb", "mlbb mistakes", "how to win mobile legends"],
    tags: ["Beginner", "Strategy", "Improvement"],
  },
  {
    id: "1",
    title: "MLBB Weekly Pass Price in India (2026)",
    slug: "mlbb-weekly-pass-price-in-india",
    game: "mlbb",
    type: "Guide",
    excerpt:
      "Learn the latest MLBB weekly pass price in India and whether it's worth buying.",
    publishedAt: "2026-01-10",
    author: "Admin",
    readingTime: "4 min read",
    image: "/blog/weekly-pass-price.png",
    featured: true,
    keywords: ["mlbb weekly pass price", "weekly diamond pass india", "cheap mlbb recharge"],
    tags: ["Pricing", "Guides", "Savings"],
  },
  {
    id: "2",
    title: "How to Buy MLBB Diamonds Safely in India",
    slug: "how-to-buy-mlbb-diamonds-safely-in-india",
    game: "mlbb",
    type: "Safety",
    excerpt:
      "Step-by-step guide to buying MLBB diamonds safely in India.",
    publishedAt: "2026-01-12",
    author: "Admin",
    readingTime: "5 min read",
    image: "/blog/buy-safely.png",
    featured: true,
    keywords: ["buy mlbb diamonds india", "safe mlbb recharge", "trusted topup site"],
    tags: ["Safety", "Tutorial", "Security"],
  },
  {
    id: "3",
    title: "Is MLBB Top-Up Legal in India?",
    slug: "is-mlbb-top-up-legal-in-india",
    game: "mlbb",
    type: "Info",
    excerpt:
      "Understand whether MLBB top-ups are legal in India.",
    publishedAt: "2026-01-05",
    author: "Admin",
    readingTime: "3 min read",
    image: "/blog/legal-india.png",
    keywords: ["mlbb legal india", "mobile legends ban status", "is mlbb top up safe"],
    tags: ["Legal", "News", "India"],
  },
  {
    id: "4",
    title: "How to Gift MLBB Diamonds to Friends (2026)",
    slug: "how-to-gift-mlbb-diamonds",
    game: "mlbb",
    type: "Guide",
    excerpt:
      "A complete guide on how to safely gift Mobile Legends diamonds to your friends using their Player ID.",
    publishedAt: "2026-02-07",
    author: "Admin",
    readingTime: "3 min read",
    image: "/blog/gift-guide.png",
    featured: true,
    keywords: ["gift mlbb diamonds", "send diamonds to friends", "mlbb gift guide"],
    tags: ["Gifting", "Tutorial", "Social"],
  },
  {
    id: "5",
    title: "Best MLBB Diamond Packages â€“ Which Gives the Most Value? (2026)",
    slug: "best-mlbb-diamond-packages-value-guide",
    game: "mlbb",
    type: "Value Guide",
    excerpt:
      "Not all MLBB diamond packages are equal. Find out which bundle gives you the most diamonds per rupee and how to save more with bonus events.",
    publishedAt: "2026-02-26",
    author: "Admin",
    readingTime: "5 min read",
    image: "/blog/best-value.png",
    featured: true,
    keywords: ["best mlbb diamond pack", "mlbb value guide", "cheapest diamonds india"],
    tags: ["Pricing", "Deals", "Analysis"],
  },
];
