export interface BlogPost {
  game: string;
  id: string;
  title: string;
  slug: string;
  type: string;
  excerpt: string;
  publishedAt: string;
  readingTime: string;
  image: string;
  featured?: boolean;
  tags?: string[];
}

export const BLOGS_DATA: BlogPost[] = [
  {
    id: "23",
    title: "Beatrix Best Build 2026: Ultimate Marksman Guide",
    slug: "heroes/beatrix-best-build-2026",
    type: "Hero Guide",
    excerpt:
      "Dominate the Gold Lane in 2026 with our ultimate Beatrix best build guide. Master all four weapons, emblems, and item strategies in Mobile Legends.",
    publishedAt: "2026-04-29",
    readingTime: "12 min read",
    image: "/blog/mlbb/heroes/beatrix-build-2026.png",
    featured: true,
    game: "mlbb",
    tags: ["beatrix", "marksman", "build", "2026"],
  },
  {
    id: "22",
    title: "Best MLBB Heroes 2026: Rank Push Meta Guide",
    slug: "best-mlbb-heroes-for-rank-push-2026",
    type: "Meta Guide",
    excerpt:
      "Discover the best MLBB heroes for rank push in 2026. Master the current meta with our top picks for solo queue and team play to reach Mythic fast.",
    publishedAt: "2026-04-24",
    readingTime: "15 min read",
    image: "/blog/mlbb/guides/best-heroes-2026.png",
    featured: true,
    game: "mlbb",
    tags: ["meta", "rank-push", "tier-list", "2026"],
  },
  {
    id: "21",
    title: "Step-by-Step Guide: How to Buy MLBB Diamonds Safely",
    slug: "step-by-step-guide-to-buy-diamonds-safely",
    type: "Tutorial",
    excerpt:
      "Want to buy MLBB diamonds but unsure how? Our 2026 step-by-step tutorial covers the entire process — from entering your Player ID to paying via UPI — for a safe, instant top-up with zero risk.",
    publishedAt: "2026-03-31",
    readingTime: "11 min read",
    image: "/blog/mlbb/guides/mlbb-buy-safely-guide.png",
    featured: true,
    game: "mlbb",
    tags: ["tutorial", "safety", "diamonds"],
  },
  {
    id: "20",
    title: "MLBB Diamond Spending Blueprint 2026 India",
    slug: "how-to-spend-diamonds-wisely-in-mlbb",
    type: "Strategy Guide",
    excerpt:
      "Stop wasting diamonds in MLBB! Master the 2026 spending blueprint to maximize your value in India. Learn the daily discount trick and best investments.",
    publishedAt: "2026-03-31",
    readingTime: "13 min read",
    image: "/blog/mlbb/guides/mlbb-wise-spending.png",
    featured: true,
    game: "mlbb",
    tags: ["diamonds", "savings", "blueprint"],
  },
  {
    id: "19",
    title: "Weekly Diamond Pass vs Direct Recharge 2026",
    slug: "weekly-diamond-pass-vs-direct-recharge",
    type: "Value Comparison",
    excerpt:
      "Weekly Diamond Pass vs direct recharge in MLBB: which is better? Read our 2026 guide to find out the best value, ROI, and how to save money in India.",
    publishedAt: "2026-03-31",
    readingTime: "12 min read",
    image: "/blog/mlbb/insights/mlbb-wdp-vs-diamonds.png",
    featured: true,
    game: "mlbb",
    tags: ["diamonds", "value", "comparison"],
  },
  {
    id: "18",
    title: "Is MLBB Worth Spending Money On? 2026 Review",
    slug: "is-mlbb-worth-spending-money-on",
    type: "Opinion",
    excerpt:
      "Should you buy diamonds in Mobile Legends? Read our honest 2026 review on whether MLBB is worth spending money on, covering Starlight and skin value.",
    publishedAt: "2026-03-31",
    readingTime: "11 min read",
    image: "/blog/mlbb/insights/mlbb-worth-it.png",
    featured: true,
    game: "mlbb",
    tags: ["opinion", "worth-it", "diamonds"],
  },
  {
    id: "17",
    title: "How to Avoid MLBB Diamond Scams 2026 Guide",
    slug: "how-to-avoid-scams-while-buying-diamonds",
    type: "Safety Guide",
    excerpt:
      "Don't get scammed! Learn how to safely buy Mobile Legends diamonds in India. Our 2026 guide covers top-up scams, fake sites, and account safety tips.",
    publishedAt: "2026-03-31",
    readingTime: "13 min read",
    image: "/blog/mlbb/guides/mlbb-avoid-scams.png",
    featured: true,
    game: "mlbb",
    tags: ["safety", "scams", "top-up"],
  },
  {
    id: "16",
    title: "How to Reduce Lag in MLBB 2026: FPS & Ping Fix",
    slug: "how-to-reduce-lag-in-mobile-legends",
    type: "Tech Guide",
    excerpt:
      "Experience zero lag in MLBB! Learn how to reduce lag, fix ping spikes, and optimize your FPS for a smooth gaming experience in our 2026 fix guide.",
    publishedAt: "2026-03-31",
    readingTime: "14 min read",
    image: "/blog/mlbb/guides/mlbb-reduce-lag.png",
    featured: true,
    game: "mlbb",
    tags: ["tech", "lag", "fps"],
  },
  {
    id: "15",
    title: "Best Ways to Spend MLBB Diamonds in 2026",
    slug: "best-ways-to-spend-diamonds-in-mlbb",
    type: "Value Guide",
    excerpt:
      "Want to maximize your MLBB diamonds? Learn the best ways to spend diamonds in 2026, including Starlight Memberships, Weekly Passes, and event draws.",
    publishedAt: "2026-03-31",
    readingTime: "15 min read",
    image: "/blog/mlbb/guides/mlbb-spend-diamonds.png",
    featured: true,
    game: "mlbb",
    tags: ["diamonds", "value", "guide"],
  },
  {
    id: "14",
    title: "How to Fix Ping Issues in MLBB 2026 Guide",
    slug: "how-to-fix-ping-issues-in-mlbb",
    type: "Tech Guide",
    excerpt:
      "Tired of 999ms lag and ping spikes in Mobile Legends? Learn how to fix ping issues, reduce latency, and optimize your network in our 2026 lag guide.",
    publishedAt: "2026-03-31",
    readingTime: "14 min read",
    image: "/blog/mlbb/guides/mlbb-fix-ping.png",
    featured: true,
    game: "mlbb",
    tags: ["tech", "ping", "lag"],
  },
  {
    id: "13",
    title: "How to Carry in Solo Queue MLBB 2026 Guide",
    slug: "how-to-carry-in-solo-queue",
    type: "Pro Strategy",
    excerpt:
      "Tired of losing with random teammates in Mobile Legends? Learn the professional secrets to carrying in solo queue with our 2026 MLBB strategy guide.",
    publishedAt: "2026-03-31",
    readingTime: "16 min read",
    image: "/blog/mlbb/guides/mlbb-solo-carry.png",
    featured: true,
    game: "mlbb",
    tags: ["solo", "carry", "strategy"],
  },
  {
    id: "12",
    title: "How to Rank Up From Epic to Mythic in MLBB: The 2026 Survival Guide",
    slug: "how-to-rank-up-from-epic-to-mythic-in-2026",
    type: "Ranking Guide",
    excerpt:
      "Stuck in Epic Hell? Break free with our definitive 2026 MLBB guide covering drafting secrets, objective control, wave management, and the mental discipline needed to reach Mythic on Indian servers.",
    publishedAt: "2026-03-31",
    readingTime: "18 min read",
    image: "/blog/mlbb/guides/mlbb-epic-to-mythic.png",
    featured: true,
    game: "mlbb",
    tags: ["ranking", "mythic", "epic"],
  },
  {
    id: "11",
    title: "How to Win More MLBB Matches 2026",
    slug: "how-to-win-more-matches-consistently",
    type: "Pro Tips",
    excerpt:
      "Improve your Mobile Legends win rate with our 2026 strategy guide. Master the mental game, drafting secrets, and elite-tier map management.",
    publishedAt: "2026-03-31",
    readingTime: "12 min read",
    image: "/blog/mlbb/guides/mlbb-win-consistently.png",
    featured: true,
    game: "mlbb",
    tags: ["tips", "win", "rank"],
  },
  {
    id: "10",
    title: "The Complete Mobile Legends Gameplay Guide: Lanes, Jungle & Objectives",
    slug: "complete-mlbb-gameplay-guide",
    type: "Game Guide",
    excerpt:
      "New to MLBB or stuck in low ranks? Our complete 2026 gameplay guide covers laning fundamentals, jungle rotation timing, Turtle/Lord priority, and the core mechanics that every Indian MLBB player needs to master.",
    publishedAt: "2026-03-31",
    readingTime: "15 min read",
    image: "/blog/mlbb/guides/mlbb-gameplay-guide.png",
    featured: true,
    game: "mlbb",
    tags: ["guide", "gameplay", "strategy"],
  },
  {
    id: "9",
    title: "How to Farm Gold Fast in MLBB 2026",
    slug: "how-to-farm-gold-fast-in-mlbb",
    type: "Strategy",
    excerpt:
      "Want to get your core items before everyone else? Learn professional strategies for farming gold fast in Mobile Legends with our 2026 guide.",
    publishedAt: "2026-03-31",
    readingTime: "7 min read",
    image: "/blog/mlbb/guides/mlbb-gold-farm.png",
    featured: true,
    game: "mlbb",
    tags: ["strategy", "farming", "gold"],
  },
  {
    id: "8",
    title: "MLBB Roles Explained 2026 Guide",
    slug: "mlbb-roles-guide",
    type: "Game Guide",
    excerpt:
      "Learn all 6 MLBB roles in our 2026 beginner guide. Master Tank, Fighter, Mage, Assassin, Marksman, and Support to build the perfect team.",
    publishedAt: "2026-03-30",
    readingTime: "5 min read",
    image: "/blog/mlbb/guides/mlbb-roles.png",
    featured: true,
    game: "mlbb",
    tags: ["guide", "roles"],
  },
  {
    id: "6",
    title: "MLBB Tricks to Rank Up Instantly 2026",
    slug: "mlbb-tricks-to-rank-up",
    type: "Pro Tips",
    excerpt:
      "Master the hidden mechanics of Mobile Legends that pro players use to dominate. Learn advanced minimap tricks and camera movement to rank up fast.",
    publishedAt: "2026-03-29",
    readingTime: "6 min read",
    image: "/blog/mlbb/guides/mlbb-tricks.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "1",
    title: "MLBB Weekly Pass Price in India 2026",
    slug: "mlbb-weekly-pass-price-in-india",
    type: "Price Guide",
    excerpt:
      "Discover the MLBB Weekly Diamond Pass price in India for 2026. Compare rewards, stack benefits, and find the cheapest way to buy MLBB diamonds.",
    publishedAt: "2026-01-10",
    readingTime: "12 min read",
    image: "/blog/mlbb/guides/weekly-pass-price.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "2",
    title: "How to Buy MLBB Diamonds Safely in India 2026",
    slug: "how-to-buy-mlbb-diamonds-safely-in-india",
    type: "Safety Guide",
    excerpt:
      "Learn how to buy MLBB diamonds safely in India. Avoid negative diamond bans and scams with our step-by-step 2026 secure top-up guide.",
    publishedAt: "2026-01-12",
    readingTime: "20 min read",
    image: "/blog/mlbb/guides/buy-safely.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "3",
    title: "Is MLBB Top Up Legal in India? 2026 Guide",
    slug: "is-mlbb-top-up-legal-in-india",
    type: "Legal Guide",
    excerpt:
      "Is Mobile Legends top-up legal in India? Read our 2026 comprehensive guide to understand the regulations, safety checks, and trusted platforms.",
    publishedAt: "2026-01-05",
    readingTime: "18 min read",
    image: "/blog/mlbb/guides/legal-india.png",
    game: "mlbb",
  },
  {
    id: "4",
    title: "How to Gift MLBB Diamonds in 2026 Guide",
    slug: "how-to-gift-mlbb-diamonds",
    type: "Guide",
    excerpt:
      "Learn how to gift MLBB diamonds instantly in 2026. Bypass the 7-day friend limit and safely send diamonds, skins, or passes using Player ID.",
    publishedAt: "2026-02-07",
    readingTime: "15 min read",
    image: "/blog/mlbb/guides/gift-guide.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "5",
    title: "Best MLBB Diamond Packages India 2026",
    slug: "best-mlbb-diamond-packages-value-guide",
    type: "Value Guide",
    excerpt:
      "Find the best MLBB diamond packages in India with our 2026 real price and value guide. Compare packages to get maximum value for your rupees.",
    publishedAt: "2026-02-26",
    readingTime: "12 min read",
    image: "/blog/mlbb/guides/best-value.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "7",
    title: "Stop Losing in MLBB: 7 Fatal Mistakes",
    slug: "stop-losing-mlbb-7-mistakes",
    type: "Gameplay Guide",
    excerpt:
      "Stuck in a lose streak? Master the 7 common MLBB mistakes that keep players in Epic rank. Learn pro map awareness and objective strategies.",
    publishedAt: "2026-03-29",
    readingTime: "15 min read",
    image: "/blog/mlbb/guides/fix-mistakes.png",
    game: "mlbb",
  },
];
