export interface BlogPost {
  game: string;
  id: string;
  title: string;
  slug: string;
  type: string;
  excerpt: string;
  publishedAt: string;
  readingTime: string;
  image: string;
  featured?: boolean;
  tags?: string[];
}

export const BLOGS_DATA: BlogPost[] = [
  {
    id: "23",
    title: "Beatrix Best Build 2026: Master the Versatile Marksman",
    slug: "heroes/beatrix-best-build-2026",
    type: "Hero Guide",
    excerpt:
      "Master Beatrix in 2026 with our ultimate MLBB build guide. Learn the best items, emblems, and weapon-switching strategies to dominate the Land of Dawn as the versatile marksman.",
    publishedAt: "2026-04-29",
    readingTime: "12 min read",
    image: "/blog/beatrix-build-2026.png",
    featured: true,
    game: "mlbb",
    tags: ["beatrix", "marksman", "build", "2026"],
  },
  {
    id: "22",
    title: "Best MLBB Heroes for Rank Push in 2026: The Ultimate Meta Guide",
    slug: "best-mlbb-heroes-for-rank-push-2026",
    type: "Meta Guide",
    excerpt:
      "Dominate the 2026 meta with our top picks for rank push in Mobile Legends. Discover the best heroes across all roles — from Jungler to Roamer — to climb from Epic to Mythic fast in India.",
    publishedAt: "2026-04-24",
    readingTime: "15 min read",
    image: "/blog/best-heroes-2026.png",
    featured: true,
    game: "mlbb",
    tags: ["meta", "rank-push", "tier-list", "2026"],
  },
  {
    id: "21",
    title: "Step-by-Step Guide: How to Buy MLBB Diamonds Safely",
    slug: "step-by-step-guide-to-buy-diamonds-safely",
    type: "Tutorial",
    excerpt:
      "Want to buy MLBB diamonds but unsure how? Our 2026 step-by-step tutorial covers the entire process — from entering your Player ID to paying via UPI — for a safe, instant top-up with zero risk.",
    publishedAt: "2026-03-31",
    readingTime: "11 min read",
    image: "/blog/mlbb-buy-safely-guide.png",
    featured: true,
    game: "mlbb",
    tags: ["tutorial", "safety", "diamonds"],
  },
  {
    id: "20",
    title: "The 2026 Diamond Spending Blueprint: How to Spend Like a Pro & Save Money",
    slug: "how-to-spend-diamonds-wisely-in-mlbb",
    type: "Strategy Guide",
    excerpt:
      "Most players waste half their diamonds. Learn the expert blueprint to spend wisely in MLBB — use the Daily Discount trick, avoid spend traps, and maximize every rupee you invest in 2026.",
    publishedAt: "2026-03-31",
    readingTime: "13 min read",
    image: "/blog/mlbb-wise-spending.png",
    featured: true,
    game: "mlbb",
    tags: ["diamonds", "savings", "blueprint"],
  },
  {
    id: "19",
    title: "Weekly Diamond Pass vs. Direct Recharge in MLBB: Which is Better?",
    slug: "weekly-diamond-pass-vs-direct-recharge",
    type: "Value Comparison",
    excerpt:
      "Weekly Pass or direct diamonds — which gives more value in India? Our 2026 comparison breaks down the cost-per-diamond, event ROI, and exactly when to choose each option.",
    publishedAt: "2026-03-31",
    readingTime: "12 min read",
    image: "/blog/mlbb-wdp-vs-diamonds.png",
    featured: true,
    game: "mlbb",
    tags: ["diamonds", "value", "comparison"],
  },
  {
    id: "18",
    title: "Is MLBB Worth Spending Money On? The 2026 Honest Review",
    slug: "is-mlbb-worth-spending-money-on",
    type: "Opinion",
    excerpt:
      "Should you buy diamonds in Mobile Legends? Our honest 2026 review explores whether MLBB is worth spending money on — covering Starlight benefits, skin ROI, and the smarter ways to recharge in India.",
    publishedAt: "2026-03-31",
    readingTime: "11 min read",
    image: "/blog/mlbb-worth-it.png",
    featured: true,
    game: "mlbb",
    tags: ["opinion", "worth-it", "diamonds"],
  },
  {
    id: "17",
    title: "How to Avoid Scams While Buying MLBB Diamonds: The 2026 Safety Guide",
    slug: "how-to-avoid-scams-while-buying-diamonds",
    type: "Safety Guide",
    excerpt:
      "Don't get scammed! Learn exactly how to buy Mobile Legends diamonds safely in India. Our 2026 guide exposes common top-up scams, fake sites to avoid, and the safety checkpoints every Indian player needs.",
    publishedAt: "2026-03-31",
    readingTime: "13 min read",
    image: "/blog/mlbb-avoid-scams.png",
    featured: true,
    game: "mlbb",
    tags: ["safety", "scams", "top-up"],
  },
  {
    id: "16",
    title: "How to Reduce Lag in Mobile Legends: The Ultimate 2026 FPS & Ping Fix",
    slug: "how-to-reduce-lag-in-mobile-legends",
    type: "Tech Guide",
    excerpt:
      "Experience zero lag in MLBB with our comprehensive 2026 fix guide. Learn how to reduce ping spikes, boost FPS on mid-range phones, and optimize your network settings for silky-smooth Indian server gameplay.",
    publishedAt: "2026-03-31",
    readingTime: "14 min read",
    image: "/blog/mlbb-reduce-lag.png",
    featured: true,
    game: "mlbb",
    tags: ["tech", "lag", "fps"],
  },
  {
    id: "15",
    title: "The Best Ways to Spend Diamonds in MLBB: Maximize Your Value",
    slug: "best-ways-to-spend-diamonds-in-mlbb",
    type: "Value Guide",
    excerpt:
      "Get the most out of every diamond you buy in Mobile Legends. Our 2026 guide covers Starlight Membership, Weekly Passes, Gacha events, and the exact spending order that gives Indian players maximum skin value.",
    publishedAt: "2026-03-31",
    readingTime: "15 min read",
    image: "/blog/mlbb-spend-diamonds.png",
    featured: true,
    game: "mlbb",
    tags: ["diamonds", "value", "guide"],
  },
  {
    id: "14",
    title: "How to Fix Ping Issues in MLBB: The 2026 Lag Fix Guide",
    slug: "how-to-fix-ping-issues-in-mlbb",
    type: "Tech Guide",
    excerpt:
      "Tired of high ping ruining your MLBB games? Our 2026 guide reveals step-by-step fixes for ping spikes, connection drops, and high latency — specifically optimized for Indian mobile network conditions.",
    publishedAt: "2026-03-31",
    readingTime: "14 min read",
    image: "/blog/mlbb-fix-ping.png",
    featured: true,
    game: "mlbb",
    tags: ["tech", "ping", "lag"],
  },
  {
    id: "13",
    title: "How to Carry in Solo Queue MLBB: The Ultimate Carry Guide",
    slug: "how-to-carry-in-solo-queue",
    type: "Pro Strategy",
    excerpt:
      "Stop relying on random teammates. Master the art of carrying Solo Queue in MLBB with our 2026 guide — covering hero picks, ganking patterns, and the psychological edge that separates Mythic players in India.",
    publishedAt: "2026-03-31",
    readingTime: "16 min read",
    image: "/blog/mlbb-solo-carry.png",
    featured: true,
    game: "mlbb",
    tags: ["solo", "carry", "strategy"],
  },
  {
    id: "12",
    title: "How to Rank Up From Epic to Mythic in MLBB: The 2026 Survival Guide",
    slug: "how-to-rank-up-from-epic-to-mythic-in-2026",
    type: "Ranking Guide",
    excerpt:
      "Stuck in Epic Hell? Break free with our definitive 2026 MLBB guide covering drafting secrets, objective control, wave management, and the mental discipline needed to reach Mythic on Indian servers.",
    publishedAt: "2026-03-31",
    readingTime: "18 min read",
    image: "/blog/mlbb-epic-to-mythic.png",
    featured: true,
    game: "mlbb",
    tags: ["ranking", "mythic", "epic"],
  },
  {
    id: "11",
    title: "How to Win More Matches Consistently in MLBB (Ultimate Ranking Strategy)",
    slug: "how-to-win-more-matches-consistently",
    type: "Pro Tips",
    excerpt:
      "Win-streaks aren't luck. Learn the system that consistently winning Mobile Legends players use — covering macro discipline, hero mastery, tilt prevention, and the winning mindset for Indian rank players in 2026.",
    publishedAt: "2026-03-31",
    readingTime: "12 min read",
    image: "/blog/mlbb-win-consistently.png",
    featured: true,
    game: "mlbb",
    tags: ["tips", "win", "rank"],
  },
  {
    id: "10",
    title: "The Complete Mobile Legends Gameplay Guide: Lanes, Jungle & Objectives",
    slug: "complete-mlbb-gameplay-guide",
    type: "Game Guide",
    excerpt:
      "New to MLBB or stuck in low ranks? Our complete 2026 gameplay guide covers laning fundamentals, jungle rotation timing, Turtle/Lord priority, and the core mechanics that every Indian MLBB player needs to master.",
    publishedAt: "2026-03-31",
    readingTime: "15 min read",
    image: "/blog/mlbb-gameplay-guide.png",
    featured: true,
    game: "mlbb",
    tags: ["guide", "gameplay", "strategy"],
  },
  {
    id: "9",
    title: "How to Farm Gold Fast in MLBB (Mobile Legends Farming Guide)",
    slug: "how-to-farm-gold-fast-in-mlbb",
    type: "Strategy",
    excerpt:
      "Outpace the enemy economy with our MLBB gold farming guide. Learn the best minion wave patterns, jungle rotation tricks, and CS management tips to get your core items faster than your opponents in 2026.",
    publishedAt: "2026-03-31",
    readingTime: "7 min read",
    image: "/blog/mlbb-gold-farm.png",
    featured: true,
    game: "mlbb",
    tags: ["strategy", "farming", "gold"],
  },
  {
    id: "8",
    title: "MLBB Roles Explained: Tank, Fighter, Mage, Assassin, Marksman, Support",
    slug: "mlbb-roles-guide",
    type: "Game Guide",
    excerpt:
      "Understand all 6 roles in Mobile Legends: Bang Bang. Our beginner-friendly 2026 guide explains what each role does, which lane they go in, and how to pick the right hero to win more games as an Indian player.",
    publishedAt: "2026-03-30",
    readingTime: "5 min read",
    image: "/blog/mlbb-roles.png",
    featured: true,
    game: "mlbb",
    tags: ["guide", "roles"],
  },
  {
    id: "6",
    title: "99% Players Don't Know These MLBB Tricks (Rank Up Instantly)",
    slug: "mlbb-tricks-to-rank-up",
    type: "Pro Tips",
    excerpt:
      "Unlock the hidden mechanics and advanced tricks that pro MLBB players use to dominate every match. These 2026 tips will transform how you play and give you the edge needed to rank up fast in India.",
    publishedAt: "2026-03-29",
    readingTime: "6 min read",
    image: "/blog/mlbb-tricks.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "1",
    title: "MLBB Weekly Pass Price in India 2026 – Is it Worth Buying?",
    slug: "mlbb-weekly-pass-price-in-india",
    type: "Price Guide",
    excerpt:
      "Discover the exact MLBB Weekly Diamond Pass price in India for 2026. We break down the total value (220+ diamonds + rewards), compare it against raw recharge, and reveal where to buy it cheapest via UPI.",
    publishedAt: "2026-01-10",
    readingTime: "12 min read",
    image: "/blog/weekly-pass-price.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "2",
    title: "How to Buy MLBB Diamonds Safely in India (The 2026 Safety Blueprint)",
    slug: "how-to-buy-mlbb-diamonds-safely-in-india",
    type: "Safety Guide",
    excerpt:
      "Protect your MLBB account from scams and negative diamond bans. Our 2026 safety guide for India covers verification checks, choosing trusted platforms, and the exact steps for a 100% safe diamond top-up.",
    publishedAt: "2026-01-12",
    readingTime: "20 min read",
    image: "/blog/buy-safely.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "3",
    title: "Is MLBB Top-Up Legal in India? The 2026 Comprehensive Guide",
    slug: "is-mlbb-top-up-legal-in-india",
    type: "Legal Guide",
    excerpt:
      "Confused about whether MLBB diamond top-ups are legal in India? We answer definitively — yes, when using authorized platforms. Learn the legal distinction, why prices are lower, and what makes a top-up safe.",
    publishedAt: "2026-01-05",
    readingTime: "18 min read",
    image: "/blog/legal-india.png",
    game: "mlbb",
  },
  {
    id: "4",
    title: "How to Gift MLBB Diamonds to Friends – The Definitive 2026 Guide (India)",
    slug: "how-to-gift-mlbb-diamonds",
    type: "Guide",
    excerpt:
      "Send MLBB diamonds or Weekly Passes to your friends instantly using just their Player ID — no 7-day friendship timer required. Our 2026 gifting guide covers every method for Indian players with secure UPI payment.",
    publishedAt: "2026-02-07",
    readingTime: "15 min read",
    image: "/blog/gift-guide.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "5",
    title: "Best MLBB Diamond Packages in India – Real Price & Value Guide (2026)",
    slug: "best-mlbb-diamond-packages-value-guide",
    type: "Value Guide",
    excerpt:
      "Find out which MLBB diamond bundle gives you the most diamonds per rupee in India. We break down the real cost-per-diamond for every package and reveal the ultimate value strategy for 2026.",
    publishedAt: "2026-02-26",
    readingTime: "12 min read",
    image: "/blog/best-value.png",
    featured: true,
    game: "mlbb",
  },
  {
    id: "7",
    title: "Stop Losing in Mobile Legends – Fix These 7 Fatal Mistakes Now",
    slug: "stop-losing-mlbb-7-mistakes",
    type: "Gameplay Guide",
    excerpt:
      "Stuck in a loss streak? Our 2026 MLBB guide identifies the 7 most common mistakes Indian Epic-rank players make — from map blindness to static item builds — and gives you the exact fixes to start winning consistently.",
    publishedAt: "2026-03-29",
    readingTime: "15 min read",
    image: "/blog/fix-mistakes.png",
    game: "mlbb",
  },
];
